# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install
        env:
          CI: true
  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn add jest 
      - run: yarn test
        env:
          CI: true
          FIREBASE_API_KEY: process.env.FIREBASE_API_KEY
          FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN
          FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL
          FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID
          FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET
          FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID
          FIREBASE_APP_ID: process.env.FIREBASE_APP_ID
          FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID
